version: "3.0"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=hospital
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p@ssw0rd2020ya
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

